---
- hosts: mailserver
  remote_user: admin
  become: yes
  become_method: sudo
  vars_files:
  - "./vars/variables.yml"

  tasks:
#Puedo incluir variables usando el módulo include_vars
#  - name: Include variables for tasks and templates
#    include_vars:
#      file: variables.yml

  - name: Epel repo is installed
    yum:
      name: epel-release
      state: present 

  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: latest

  - name: write postfix config file
    template:
      src: ./templates/postfix-main.cf.j2
      dest: /etc/postfix/main.cf
    notify:
      - Restart postfix

  - name: ensure postfix is running
    service:
      name: postfix
      state: started
      enabled: yes
      
  - name: enable imap in dovecot
    lineinfile:
      path: /etc/dovecot/dovecot.conf
      line: 'protocols= imap pop3 lmtp'
      state: present

  - name: copy dovecot mail configuration
    copy: 
      src: ./templates/10-mail.conf
      dest: /etc/dovecot/conf.d/10-mail.conf
      force: yes
    notify: 
      - Restart dovecot

   - name: Dovecot running and enabled
    service:
      name: dovecot
      state: started
      enabled: yes

  - name: Configure squirrelmail
    template:
      src: ./templates/squirrelmail.conf.j2
      dest: /etc/squirrelmail/config.php
      owner: root
      group: root
      mode: 0640

  - name: Apache running and enabled
    service:
      name: httpd
      state: started
      enabled: yes
      
  - name: open firewall ports       
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - smtp
      - imap
      - http

  handlers: 
  - name: Restart postfix
    service:
      name: postfix
      state: restarted
      enabled: yes 

  - name: Restart dovecot
    service:
      name: dovecot
      state: restarted
      enabled: yes   

